# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       sailfishos-patch-maths-in-alarm

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    maths-in-alarm
Version:    1.0
Release:    2
Group:      Applications/Productivity
License:    GPL2
URL:        http://me.medesimo.eu
Source0:    %{name}-%{version}.tar.bz2
Source100:  sailfishos-patch-maths-in-alarm.yaml
Requires:   patchmanager

%description
A simple way to ensure that you will get up tomorrow :)


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/patchmanager
# >> files
# << files
